# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c30902be418ed97b8d59668a3ba2e7a"
name = "Red Ruby"
handle = "red-ruby"
application_url = "https://departments-conversation-hwy-saturday.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extension-test-sj.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,read_checkouts,read_discounts,read_orders,read_products,read_themes,write_checkout_branding_settings,write_checkouts,write_discounts,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
  "https://departments-conversation-hwy-saturday.trycloudflare.com/auth/callback",
  "https://departments-conversation-hwy-saturday.trycloudflare.com/auth/shopify/callback",
  "https://departments-conversation-hwy-saturday.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
