# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c30902be418ed97b8d59668a3ba2e7a"
name = "features-test"
handle = "features-test"
application_url = "https://game-rental-opinion-apparently.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extension-test-sj.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://game-rental-opinion-apparently.trycloudflare.com/auth/callback",
  "https://game-rental-opinion-apparently.trycloudflare.com/auth/shopify/callback",
  "https://game-rental-opinion-apparently.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
